# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verb_are',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=30)),
                ('tense', models.CharField(choices=[('Presente', 'Presente'), ('Passato Prossimo', 'Passato Prossimo'), ('Imperfetto', 'Imperfetto'), ('Trapassato Prossimo', 'Trapassato Prossimo'), ('Futuro Semplice', 'Futuro Semplice'), ('Futuro Anteriore', 'Futuro Anteriore'), ('Congiuntivo Presente', 'Congiuntivo Presente'), ('Congiuntivo Passato', 'Congiuntivo Passato'), ('Congiuntivo Imperfetto', 'Congiuntivo Imperfetto'), ('Congiuntivo Trapassato', 'Congiuntivo Trapassato'), ('Condizionale Presente', 'Condizionale Presente'), ('Condizionale Passato', 'Condizionale Passato')], max_length=50)),
                ('first_person_singular', models.CharField(max_length=30)),
                ('second_person_singular', models.CharField(max_length=30)),
                ('third_person_singular', models.CharField(max_length=30)),
                ('first_person_plural', models.CharField(max_length=30)),
                ('second_person_plural', models.CharField(max_length=30)),
                ('third_person_plural', models.CharField(max_length=30)),
            ],
        ),
    ]
