# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-12 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_verb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verb_erelineitem',
            name='verb',
        ),
        migrations.DeleteModel(
            name='Verb_ERE',
        ),
        migrations.DeleteModel(
            name='Verb_ERELineItem',
        ),
    ]
