# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-25 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_verb', '0003_verb_ere_verb_erelineitem_verb_ire_verb_irelineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb_irelineitem',
            name='first_person_plural',
            field=models.CharField(default='no conjugation yet', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='verb_irelineitem',
            name='first_person_singular',
            field=models.CharField(default='no conjugation yet', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='verb_irelineitem',
            name='second_person_plural',
            field=models.CharField(default='no conjugation yet', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='verb_irelineitem',
            name='second_person_singular',
            field=models.CharField(default='no conjugation yet', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='verb_irelineitem',
            name='third_person_plural',
            field=models.CharField(default='no conjugation yet', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='verb_irelineitem',
            name='third_person_singular',
            field=models.CharField(default='no conjugation yet', max_length=30, null=True),
        ),
    ]
